package ntnu.idi.idatt2106.pilt.features.notebook;

import ntnu.idi.idatt2106.pilt.features.stoppingplace.model.Stoppingplace;
import ntnu.idi.idatt2106.pilt.features.user.model.Student;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * Repository for managing Notebook entities.
 * <p>
 * Extends JpaRepository to get standard CRUD operations (save, findById, delete, etc.)
 * for free. Custom query methods are generated by Spring Data JPA from method names.
 */
@Repository
public interface NotebookRepository extends JpaRepository<Notebook, Long> {

    List<Notebook> findAllByStudentOrderByStoppingPlaceRequiredStarsAsc(Student student);

    Optional<Notebook> findByStudentAndStoppingPlace(Student student, Stoppingplace stoppingPlace);

    boolean existsByStudentAndStoppingPlace(Student student, Stoppingplace stoppingPlace);

    List<Notebook> findAllByStudentClassroomId(Long classroomId);

    List<Notebook> findAllByStudentClassroomIdAndReflectionsIsNotNull(Long classroomId);
}
